### ISSUE TITLE
[Question] What approach should I use to getInitialUri only once?

### ISSUE THREAD

**Issue by ManuLpz4** [avioli/uni_links#107]
Hi guys, hope you are doing well 😁

I'm implementing uni_links in both Android and iOS and I'm facing the following issue:
I'm checking the initialUri in the initState of the onboarding (cause I use it to login the user tapping in an email link) and then I listen the subscription because sometimes the user close the app and tap the link and sometimes the app is already started when the tap occurs. Am I clear?

The problem comes when I try to logout the user and when I go to the onboarding it checks again the initialUri so logs in the user again🤣

Any suggestion? Please and thank you!

**Comment by avioli** [comment]
I would suggest you add a global flag that you've handled the initial link.

**Comment by ManuLpz4** [comment]
Isn't it a bad practice? (the global variable)

**Comment by avioli** [comment]
If you are building a library - yes.

If you are building your own app - you can do whatever you want!

**Comment by ManuLpz4** [comment]
Yes, but I need to keep it healthy cause can be error prone and more if you're working with a team I think

**Comment by avioli** [comment]
If you are building a medium-sized to big app, especially working in a team, then you are using some kind of a state store that's shared throughout your app via a provider or some other way - use that.

**Comment by ManuLpz4** [comment]
Ok, understood 👍🏻

Thank you :)
