### ISSUE TITLE
Flutter Supports: application:continueUserActivity:restorationHandler

### ISSUE THREAD

**Issue by jeprojects** [avioli/uni_links#11]
In your readme it states:

> // NOTE: Necessary, until Flutter supports
> //       `application:continueUserActivity:restorationHandler` within the
> //       `FlutterPlugin` protocol.
> 

I can see that Flutter now supports this callback: https://docs.flutter.io/objcdoc/Protocols/FlutterPlugin.html#/c:objc(pl)FlutterPlugin(im)application:continueUserActivity:restorationHandler:

Do we still need to add the ios related code?

**Comment by avioli** [comment]
I'll check and update the docs, if that's the case.

**Comment by avioli** [comment]
Very sorry for the super late response.

@jeprojects adding the code won't hurt, but is no longer necessary as you pointed.

I've removed the note in the README and the code from the example's AppDelegate.m

Thanks.
