### ISSUE TITLE
iOS Universal linking doesn't seem to work 

### ISSUE THREAD

**Issue by nourski** [avioli/uni_links#132]
I can't seem to get iOS universal links working. I've tried everything - deleting & re-installing, upgrading version number, trying different devices, simulator & real, and in each case the links open up in Safari instead of opening the app. Here are the steps I have taken to setup universal links:

1. Uploaded apple-app-site-association to an https server with json content-type. You can see per the attached that it is appearing on Apple's CDN: 

<img width="544" alt="Screen Shot 2021-08-29 at 12 40 35 PM" src="https://user-images.githubusercontent.com/34037110/131258332-13454451-6043-4ac8-b20f-6b5ac6904b3c.png">

I also validated the apple-app-site-association file via https://branch.io/resources/aasa-validator/ (worth noting that I was not able to validate with Apple's appsearch-validation-tool - received error: "Could not extract required information for Universal Links.")

2. Added the associated domain in my project capabilities:

<img width="1050" alt="Screen Shot 2021-08-28 at 12 13 16 PM" src="https://user-images.githubusercontent.com/34037110/131258398-5d08026e-1db0-4ccc-a687-669acdad1b2a.png">

Opening with /usr/bin/xcrun simctl openurl or clicking on the url on my mobile device (tried from notes app) still opens the url in safari instead of opening the app. I also followed the troubleshooting tips here: https://www.wwt.com/article/using-sysdiagnose-on-ios-to-troubleshoot-universal-links/ and found from my phone analytics logs that the app is not even reading the AASA file. 

What could I be missing? Has anyone managed to get iOS universal linking to work?

**Comment by kmoreau** [comment]
Hello,

Do you have add :

 "apps": [],
 
 in your file 'apple-app-site-association' ?

"The apps key in an apple-app-site-association file must be present and its value must be an empty array, as shown in Listing 6-1."
https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html#//apple_ref/doc/uid/TP40016308-CH12-SW2

Also check if you check 'Associated Domains' on your provisioning profile :) 

I use the example code and it works on emulator and real device (via QRCode).

**Comment by nourski** [comment]
> Hello,
> 
> Do you have add :
> 
> "apps": [],
> 
> in your file 'apple-app-site-association' ?
> 
> "The apps key in an apple-app-site-association file must be present and its value must be an empty array, as shown in Listing 6-1."
> https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html#//apple_ref/doc/uid/TP40016308-CH12-SW2
> 
> Also check if you check 'Associated Domains' on your provisioning profile :)
> 
> I use the example code and it works on emulator and real device (via QRCode).

@kmoreau thanks for the reply! The format I have for the apple-app-site-association file is following the newest format according to apple documentation. See here: https://developer.apple.com/documentation/xcode/supporting-associated-domains. That said, I also tried the former format and it did not work either. 

Also the attached shows 'associated domains' included in my provisioning profile. 

<img width="371" alt="Screen Shot 2021-09-02 at 5 34 42 PM" src="https://user-images.githubusercontent.com/34037110/131919737-4777e3c7-653d-4c9e-b1d3-e733a4b5edd4.png">


Which example code did you test with? 

Thanks again!

**Comment by nourski** [comment]
> Hello,
> 
> Do you have add :
> 
> "apps": [],
> 
> in your file 'apple-app-site-association' ?
> 
> "The apps key in an apple-app-site-association file must be present and its value must be an empty array, as shown in Listing 6-1."
> https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html#//apple_ref/doc/uid/TP40016308-CH12-SW2
> 
> Also check if you check 'Associated Domains' on your provisioning profile :)
> 
> I use the example code and it works on emulator and real device (via QRCode).

@kmoreau thanks so much for your response! I actually figure out the issue and it was a rookie mistake on my end. Just for reference in case anyone else runs into this, I had only created entitlements for profile - didn't even notice I wasn't on the "all" tab on Xcode. Once I created for all (debug, release, profile) everything worked as expected.
