### ISSUE TITLE
Using a custom URL scheme, after waking up the app from the background, the link information cannot be obtained,

### ISSUE THREAD

**Issue by kimmy-wang** [avioli/uni_links#134]
I'm using [https and custom schemes] and am testing
on my [iPhone xs max],
which is running [iOS14.8].

Using a custom URL scheme, after waking up the application from the background, the link information cannot be obtained. Using the https scheme, after waking up the application from the background, the link information can be obtained.

**Comment by pynner** [comment]
What was the solution to this?

**Comment by devsideal** [comment]
Solution?
