### ISSUE TITLE
Video link of WWDC 2015 Session 509 needs to be updated

### ISSUE THREAD

**Issue by aaronkelton** [avioli/uni_links#158]
For the life of me, I cannot find this video anywhere. It's as if it's been scrubbed from the internet. The next best thing I've found are the slides from the talk. https://devstreaming-cdn.apple.com/videos/wwdc/2015/5091mxk00t/509/509_seamless_linking_to_your_app.pdf

> I strongly recommend watching the [Apple WWDC 2015, session 509 - Seamless Linking to Your App](https://developer.apple.com/videos/play/wwdc2015/509/) to understand how the Universal Links work (and are setup).

Could someone with a link to the talk please update this?

**Comment by avioli** [comment]
Apple removes videos that no longer are best practices, so I guess it is not the best source any more.

Having said that you can find it in the Internet Archive - https://archive.org/details/wwdc2015videos
