### ISSUE TITLE
applink not working on ios

### ISSUE THREAD

**Issue by shinxxxxwon** [avioli/uni_links#176]
I am developing an app using `universal link` and `app link`.  
You are enrolled in the apple developer program.  

**how i tried**  
- Register `Associated Domains`.  
[![enter image description here][1]][1]

- Modify `Info.plist`  
```
...
<dict>
      <key>CFBundleTypeRole</key>
      <string>Editor</string>
      <key>CFBundleURLName</key>
      <string>m.mydomain.com</string>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>https</string>
      </array>
    </dict>
...
```

  [1]: https://i.stack.imgur.com/jZySw.png

- Create an `apple-app-site-association` file (I did not append it to the .json name)  
```
{
    "applinks": {
        "apps": [],
        "details": [
            {
                "appID": "<TeamID>.<Bundle Identifier>",
                "paths": ["/test/connect.asp"]
            },
        ]
    }
}
```

Android works normally, but `Universal link` does not work in IOS.

**Comment by shinxxxxwon** [comment]
I solved it by processing applecation/json for the AASA file on the IIS server.

**Comment by HusseinReda97pro** [comment]
> I solved it by processing applecation/json for the AASA file on the IIS server.

I didn't understand the solution?

**Comment by austincparker** [comment]
> I solved it by processing applecation/json for the AASA file on the IIS server.

what does this mean?
