### ISSUE TITLE
Can't get it to work on Android with subdomain

### ISSUE THREAD

**Issue by astheras** [avioli/uni_links#189]
I'm using https schemes and am testing
on my samsung s22,
which is running Android 13

and i cant make linkStream.listen to fire. 

manifest 

```
            <intent-filter
                android:autoVerify="true"
                >
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:scheme="https"
                    android:host="testshare.host.us"
                />
            </intent-filter>
```
init code 

```dart
 Future<void> _initUniLinks() async {
    try {
      final String? initialLink = await getInitialLink();
      if (initialLink != null) {
        processLink(initialLink);
      }
    } on PlatformException {
      print('DeepLinksService PlatformException:');
    }
    _subUniLinks = linkStream.listen(
      processLink,
      onError: (err) {
        print('DeepLinksService error: $err');
      },
    );
  }
```
and when i tap on link on messengers, processLink never fires. What i'm doing wrong? Thx for an answer

**Comment by astheras** [comment]
not actual, that is because of andriod 13

**Comment by rvharjinderbains** [comment]
@astheras Did you get any solution. I am also facing same in Android 13

**Comment by ayushsingh363** [comment]
any updates? I am facing the same issue on android 14

**Comment by vichuer** [comment]
Actually linkStream.listen is working but only for the first time. After the app is terminated or exited then that is not working (Android 13). Anyone got any solution?

**Comment by rvharjinderbains** [comment]
Hi all, I have followed this official documentation:- https://developer.android.com/training/app-links/deep-linking. And it is working fine. If you are getting specific error then please share.

**Comment by avioli** [comment]
This package is now marked as discontinued and `app_links` recommended replacement.
