### ISSUE TITLE
uni_link worked for me on Android but I couldn't get it to work on IOS

### ISSUE THREAD

**Issue by AbdullohRazzoqov** [avioli/uni_links#195]
![photo_2024-01-11 16 05 14](https://github.com/avioli/uni_links/assets/113353554/c37a5fc2-83e7-4c28-8b7c-7eb72a3507e9)

I have a shipping app. A map is installed to select the point of shipment and reception of cargo. The bottom line is that I want to analyze geolocation from messengers (eg whatsapp, telegram). How can I show my application in the "Open" and "Share" lists? Please help me. I am new to Flutter. I found a solution with uni_links for Android but I can't use IOS

to the AndroidManifest.xml file:
Adding 
`<data android:scheme="geo" /> solved it.`
I don't understand what to add to Info.plist for Ios

**Comment by avioli** [comment]
This package is now marked as discontinued and `app_links` recommended replacement.
