### ISSUE TITLE
Migrate to `package:web` to support WASM

### ISSUE THREAD

**Issue by IchordeDionysos** [avioli/uni_links#197]
The short version:
- Migrate usage of dart:html to package:web
- Migrate usage of dart:js, dart:js_util, and package:js to dart:js_interop

This will allow compiling to WASM engine instead of just JavaScript on web.

Full migration guide: https://dart.dev/interop/js-interop/package-web

**Comment by avioli** [comment]
This package is now marked as discontinued and `app_links` recommended replacement.
