### ISSUE TITLE
getInitialUri() not fetching uri when app is in background.

### ISSUE THREAD

**Issue by Vivek-shetty** [avioli/uni_links#20]
Your library is really good its working fine when app creates a new instance while entering to the app through deep link but in my case when app existing in the background if i entered that app through some uri by deepLinking the getInitialUri() not fetching that url.

**Comment by chenxianqi** [comment]
Your question may be the same as mine.https://github.com/avioli/uni_links/issues

**Comment by chenxianqi** [comment]
GetInitialUri () will get what it deserves only when it's cold-started, it won't get when it's opened again in the background, and it won't get results when it's monitored.

**Comment by chenxianqi** [comment]
No problem with Android

**Comment by Vivek-shetty** [comment]
I have issue in android only here i am using deep linking for resetting password so when user get the reset password link to his mail he will minimised the app and open the URL through gmail that time uni_links not fetching the URL

**Comment by TBG-FR** [comment]
You will have to use the link stream. `getInitialUri()` is only useful for when you open the app by clicking on a link. If the app is already open, you need to use the following :
```
getLinksStream().listen((String link)
{
    // handle link here
}, onError: (err)
{
    // handle error here
});
```
