### ISSUE TITLE
NOt compile with gradle 8.3

### ISSUE THREAD

**Issue by JgomesAT** [avioli/uni_links#200]
We have an erro to build with gradle 8.3:

> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@14c90df3 of type BuildFlowService.Parameters
   > A problem occurred configuring project ':uni_links'.
      > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
         > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

           If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.
           
   It's necessary to add the namespace in the build.gradle of this library

**Comment by sergdeus** [comment]
This package is no longer supported.
I switched to this package:
https://pub.dev/packages/app_links

It took 10 minutes.

**Comment by avioli** [comment]
This package is now marked as discontinued and `app_links` recommended replacement.
