### ISSUE TITLE
Please update compileSdkVersion

### ISSUE THREAD

**Issue by thearaks** [avioli/uni_links#202]
The Android compileSdkVersion is still set to 29, please update it to at least 33 otherwise it can cause issues with the Android Gradle Plugin, for example when changing the target language level:
```
Could not determine the dependencies of task ':flutter_app_badger:bundleLibCompileToJarDebug'.
> Could not create task ':flutter_app_badger:compileDebugJavaWithJavac'.
   > In order to compile Java 9+ source, please set compileSdkVersion to 30 or above
```

**Comment by martinogarrizzo5** [comment]
Please, I would really like to have this small update too!

**Comment by avioli** [comment]
This package is now marked as discontinued and `app_links` recommended replacement.
