### ISSUE TITLE
issue on android 12

### ISSUE THREAD

**Issue by AgMarwanAg** [avioli/uni_links#203]
I have set all setting of applink correctly in mainafest 
I also published the **.well-known/assetlinks.json** to my server and added the sh256 and package_name
every thing works fine on andoid <12 
but when I tried the app on android 12 I had to open app setting and allow support web addresses manually otherwise link is opining on the browser

`<intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
         <data
          android:scheme="https"
          android:pathPrefix="/ad/"
          android:host="mysite.com" />
      </intent-filter>`

**Comment by avioli** [comment]
This package is now marked as discontinued and `app_links` recommended replacement.
