### ISSUE TITLE
Is this repository actively being maintained

### ISSUE THREAD

**Issue by vivaan-vama** [avioli/uni_links#205]
I want to integrate unilinks with flutter in my app but it seems the last commit was 2 years ago. Wondering if this repo is being maintained or not? Apparently there are many open issues here which have not been updated in a long time.

Please suggest.

**Comment by yadsbah** [comment]
I recommend using app_links since this one is outdated

**Comment by avioli** [comment]
No. It is now marked as discontinued and `app_links` recommended replacement.
