### ISSUE TITLE
Unsupported Class File Version in uni_links Android Compilation

### ISSUE THREAD

**Issue by sauravcodexlancers** [avioli/uni_links#206]
**Error Message:**
```dart
Could not compile build file '/Users/imac/.pub-cache/hosted/pub.dev/uni_links-0.5.1/android/build.gradle'.
> startup failed:
  General error during conversion: Unsupported class file major version 63
```

** Description:**
The error indicates that the uni_links package is trying to compile a file (build.gradle) but encounters a problem due to an unsupported class file major version (version 63). This version is likely incompatible with the Java version expected by the Android build system.

**Probable Cause:**
The error suggests that the class files contained in the uni_links package are compiled using a Java version that is not supported by the Android build system.

**Possible Solution:**
Ensure that you're using a compatible version of Java, typically Java 8 (JDK 1.8), as the Android build system supports this version.
1. Update your Java Development Kit (JDK) to version 8 or newer.
2. Clean the Gradle cache by deleting the contents of the ~/.gradle/caches/ directory to remove any cached files that may be causing conflicts.
3. Verify that you're using the latest version of the uni_links package, as updates may include fixes for compatibility issues.

**Request for Package Update:**
Additionally, if the issue persists after trying the above steps, consider reaching out to the package maintainer through GitHub's bug section. Request an update to the uni_links package to ensure compatibility with newer versions of Java and the Android build system.

**Comment by avioli** [comment]
This package is now marked as discontinued and `app_links` recommended replacement.

**Comment by sauravcodexlancers** [comment]
Thank you for your response.
