### ISSUE TITLE
Mark as discontinued on pub.dev

### ISSUE THREAD

**Issue by MrAlek** [avioli/uni_links#207]
As this package hasn't been updated for 3 years, @avioli can you please mark the package as discontinued on `pub.dev`? This way it shows up as discontinued when running `pub outdated` which is helpful to anyone using the package in their app.

<img width="862" alt="Skärmavbild 2024-04-23 kl  08 55 06" src="https://github.com/avioli/uni_links/assets/1496135/27cb1b16-70b5-4134-9d92-ac26a1d9a8fb">

**Comment by avioli** [comment]
Done

**Comment by MrAlek** [comment]
Thank you @avioli 🙏
