### ISSUE TITLE
ios routing does not work

### ISSUE THREAD

**Issue by ahmadkhedr** [avioli/uni_links#25]
I am using this tutorial to implement the plugin 
https://peb.si/deep-links-flutter/
and it works perfectly with andriod, However, on ios the link does not direct me to the screen that I want to be displayed if the parameters matches the values that I have inserted in the method :

```dart
 void handleLink(Uri link) {
	var parameters = link.pathSegments;
	// we now have the parameters object to work with and can check the path segments!
	// e.g if we're sending https://peb.si/inbox/1 meaning 'open conversation #1' we can handle it like this:

	if (parameters[0] == "inbox" && parameters[1] != null) {
		Navigator.push(
			context,
			MaterialPageRoute(
				builder: (context) => ChatPage(
					id: int.parse(parameters[1]))));
	}
} 
```

and it just direct me to the home screen of the app instead.
How Can I solve this issue?!
Thanks in advance :)

**Comment by avioli** [comment]
I haven't written, nor followed that guide. Try reaching Thomas Lock and as him.
