### ISSUE TITLE
Link is not received when app is started by Universal Link in IOS

### ISSUE THREAD

**Issue by quentinleguennec** [avioli/uni_links#3]
When using Universal link in IOS the listener ```getUriLinksStream``` is receiving the the link correctly, but ```getInitialUri``` is not reiceving it. Any idea and what could cause this issue?

**Comment by eddywm** [comment]
You can't expect to have initially the link unless the app is linked straight from a cold start.
That's the reason why you have to listen to both the initial and most importantly the stream for after start up linking.

**Comment by quentinleguennec** [comment]
Yes, that's what we are doing. It's working fine for Android (we get the link both from initial and stream), but on IOS we only get it from stream (i.e. we don't get the initial).

**Comment by quentinleguennec** [comment]
I just did another test and it's also working fine with a Custom URL schemes, it's just with the Universal Link that there is this issue.

**Comment by blaneyneil** [comment]
can confirm that on iOS and with universal links (via firebase dynamic links) getInitialUri() always returns null on cold starts.   after the cold start then getUriLinksStream() works exactly like it should.

**Comment by eddywm** [comment]
@blaneyneil That's exactly the behavior I observed, I ended up writing code to handle those 2 cases.

**Comment by blaneyneil** [comment]
how exactly did you get `getInitialUri` to work?  i don't mean in conjunction with `getUriLinksStream` - i can't get `getInitialUri` to ever return a value.

**Comment by eddywm** [comment]
Remember you are listening to upcoming events from other apps there are 2 main cases : 

1. Your app was already up when it's being linked to here, the `getInitialUri`  won't return anything, that's the reason why here you have to subscribe to an event listening for changes.

2. Your app is called from a cold start : Here the `getInitialUri` will return something.

So handle the two cases in your logic code. I have somthing like this : 

```
 /// When the Initial  URL SCHEME didn't have initial data :: Listen for incoming data
 StreamSubscription _uniLinkSubscriber;
      _uniLinkSubscriber = getUriLinksStream().listen((Uri uri) {
}

/// In case the Initial  URL SCHEME  came already with data
var initialURI = await getInitialUri();
```

**Comment by blaneyneil** [comment]
i know - that's the problem.  i'm doing exactly that.  on iOS with a universal link (firebase dynamic links)   `await getInitialUri()` always returns null.  i'm talking rebooting an actual device, playing around on other apps for a while, then going to my email to click the deep link.  

i actually log the value to a db since the terminal isn't available for prints after being obviously terminated.

**Comment by quentinleguennec** [comment]
@eddywm What's not working is the step 2, but only for Universal links (if you use a custom URL scheme it works as expected). But for Universal Links `getInitialUri` always returns null.
