### ISSUE TITLE
Nullability issue in IOS

### ISSUE THREAD

**Issue by deandreamatias** [avioli/uni_links#37]
**Describe the bug**
When build app with this plugin for ios, a buildtime show 2 warnings:

 - UniLinksPlugin.h:4:4: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

- UniLinksPlugin.h:7:33: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
Block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

**Posible solutions generated for XCode**
For two cases:
- Insert '_Nullable' if the block pointer may be null
- Insert '_Nonnull' if the block pointer should never be null

**Smartphone (please complete the following information):**
 - Device: iOS Simulator
 - OS: target iOS8.0
- Plugin version: 0.2.0

**Additional context**
This error happend in XCode build and in Codemagic.

**Comment by ened** [comment]
Fixed in #42
