### ISSUE TITLE
AppDelegate.m install when Swift is enabled

### ISSUE THREAD

**Issue by blaneyneil** [avioli/uni_links#4]
not a bug - this package is great.  the problem i'm having, as someone who knows zero Swift, is how to support universal links when your Flutter app has Swift support enabled.   there is no AppDelegate.m anymore, but rather an AppDelegate.swift.  and there is now Runner-Bridging-Header.h instead of main.m and AppDelegate.h.

fyi, the only reason i had to include Swift support in the build is because of package contacts_service.

**Comment by eddywm** [comment]
Hey @blaneyneil did you find a way of using it with Swift ? I am having the same problem.

**Comment by blaneyneil** [comment]
nope, i abandoned swift support since it was creating problems with other packages.  the recent push makes it work in Obj C flutter projects now though.

**Comment by avioli** [comment]
I know this is waaay overdue, but if anyone looks into this (closed) issue #8 might be of some help.
