### ISSUE TITLE
How can i do when the user doesn't have the app, the unilink open the app(or play) store into app page

### ISSUE THREAD

**Issue by lucas-sesti** [avioli/uni_links#59]
I'm using unilinks and am testing
on my iOS Simulator
which is running iOS 13.

When i execute the command: ▶ /usr/bin/xcrun simctl openurl booted "lejour://profile"
i got this error: An error was encountered processing the command (domain=NSOSStatusErrorDomain, code=-10814):
The operation couldn’t be completed. (OSStatus error -10814.)

I wanna know if have any way to catch this error and redirect to app store or play store in app page

**Comment by avioli** [comment]
Unfortunately you cannot with custom schemes via `openurl`. The only way to catch the error is if the app invoking it is another one of yours.

You can use `https` schemes for this and have a webpage that offers links to the app stores, when the app is not yet installed, while when the app is, the https link will invoke the app.

**Comment by simplenotezy** [comment]
@avioli can you share some javascript code of how to open the app store when pressing the link, if the app is not installed?

**Comment by FeelHippo** [comment]
@avioli Hi we are also in the same situation, and some extra documentation/snippets would be greatly appreciated. Thank  you!
