### ISSUE TITLE
Not working with Facebook ( keep using it's internal App Browser )

### ISSUE THREAD

**Issue by heshaShawky** [avioli/uni_links#65]
**Describe the bug**
The plugin works great on WhatsApp! but not on Facebook ( using its in-app browser but my app listed on the options button on the top right corner  ) and on messenger it's actually weird when I click the link jumps to the in-app browser too, but when clicking the thumbnail of the link works fine!!!!

**To Reproduce**
1. I'm using App Links https with my domain **https://carstime.republic-news.com/**
2. I added the Facebook meta tags but didn't notice any difference actually.

**Expected behavior**
That is working with Facebook at least on the correct way not opening the in-app browser.

**Smartphone (please complete the following information):**
 - I tested this on Xiaomi note 8 pro
 - OS: Android 9

**Additional context**
I didn't implement code as I don't think it's the problem as  I'm only now the link nothing more for testing.

**Comment by heshaShawky** [comment]
Thanks, I have fixed this, was an issue with Facebook Meta tags, ( You need to implement this as a required step or not going to work  )

**Comment by prasid444** [comment]
@heshaShawky  can you share what was the exact issue in the meta tag? I am facing similar issue

**Comment by heshaShawky** [comment]
> @heshaShawky can you share what was the exact issue in the meta tag? I am facing similar issue

Check this out in [here](https://developers.facebook.com/docs/applinks/metadata-reference/)

**Comment by anisalibegic** [comment]
@heshaShawky Can you show please your configuration (both meta tags and intent-filter)? I just can't get it to work...

**Comment by RohithKilaparthi** [comment]
@heshaShawky I have added all the required meta tags. 
From the Facebook app, it shows a 404 error on iOS, whereas it does work well on android.

Any suggestions?

**Comment by Tomal9924** [comment]
> @heshaShawky I have added all the required meta tags. From the Facebook app, it shows a 404 error on iOS, whereas it does work well on android.
> 
> Any suggestions?

can you please share the manifest file?
