### ISSUE TITLE
All links blocked

### ISSUE THREAD

**Issue by CauliflowerGoer** [avioli/uni_links#72]
I'm using  custom scheme and am testing on my iPhone11
 
All links blocked,  Unable to get feedback when interacting with third-party apps

Is there any solution? I don't understand object-c
[UniLinksPlugin.m#L68](https://github.com/avioli/uni_links/blob/db29c16e6a1bff54010883958db67d0bd2738067/ios/Classes/UniLinksPlugin.m#L68)

**Comment by yiiim** [comment]
I also encountered this problem

**Comment by sayunara888** [comment]
敢问老哥是怎么解决的

**Comment by CauliflowerGoer** [comment]
> 敢问老哥是怎么解决的

弃用  uni_links ,  这个得 IOS 工程师解决,  我不懂....

**Comment by CauliflowerGoer** [comment]
> 我也遇到了这个问题

哎-   现在解决没
