### ISSUE TITLE
Support for null-safety?

### ISSUE THREAD

**Issue by alfredo-handcash** [avioli/uni_links#90]
Hi! First of all, thank you for your work and time creating this package, is amazing and help me a lot of times!!

There are any plan to migrate this package to null-safety? I think this is a package that another packages depends on, so there are a roadmap to be migrated?

Thank you!

**Comment by IchordeDionysos** [comment]
@avioli @hacker1024 I would appreciate if this would be merged 👍 

Also, the Dart/Flutter team already encourages publishing the migrated packages: See this blog post.
