### ISSUE TITLE
Apps not installed support issue?

### ISSUE THREAD

**Issue by yusriltakeuchi** [avioli/uni_links#94]
I have a case in app link. So when the user is not installed the application, it will be redirect to the playstore or appstore. But if already installed, uni_links works fine.

Can you give me suggestions to handle this case ?

Thank you

**Comment by avioli** [comment]
If you use `https` scheme - create a page for the same path and render some markup to invite your users to install the app from either store.

So if your app handles `https://my-fancy-app.com/page/123/` then have something that either renders whatever `/page/123/` is supposed to be or have a redirect to another page that shows links to both AppStore and Play Store. Then, once users install the app it will handle any future links as expected.

Neither platform allows to redirect to anything after a successful app install.
