### ISSUE TITLE
How do I set dynamic host?

### ISSUE THREAD

**Issue by Kimhak-Loem** [avioli/uni_links#97]
Hi,

Is there anyone encounter or trying to have dynamic deep link host?
For example I have multiple host with a similar pattern as bellow
- https://test1.example.com
- https://test2.example.com
- https://test3.example.com

I'm wondering if we can do this with uni_link or use other way? Your help would be appreciated!

**Comment by avioli** [comment]
As far as I know you have to specify host for any and all `https` schemes, so this is a NO to your question.

**Comment by Kimhak-Loem** [comment]
@avioli thank you for your response. Actually, it's possible to do using App Linking(Android) & Universal Link(iOS). With above example, we need to provide the json verification file (assetlinks.json or apple-app-site-association) in domain https://example.com.

Anyway, thank you again for your support.
